# [Settings]
# ID = "39805795-46cd-4c33-a281-4fe43ba85b43"
[build]
  publish = "public/"

[context.production]
  CONTENTFUL_URL = 'cdn.contentful.com'

[context.staging] # 'staging' is a branch name
  CONTENTFUL_URL = 'preview.contentful.com'

[context.dev]
  CONTENTFUL_URL = 'cdn.contentful.com'

